[project]
name = "vacuum-floor-switch"
version = "0.1.0"
description = ""
authors = [
    {name = "Uwe Jäger",email = "uwe.jaeger@valiton.com"}
]
readme = "README.md"
requires-python = "3.13.*"
dependencies = [
    "fastapi[standard] (>=0.116.1,<0.117.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "python-miio (>=0.5.12,<0.6.0)"
]

[tool.poetry]
packages = [{include = "vacuum_floor_switch", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
